CREATE SCHEMA `SportsAnalytics`;

USE `SportsAnalytics`;

CREATE TABLE `season` (
`SEASON_ID` BIGINT NOT NULL,
`SEASON` VARCHAR(50),
PRIMARY KEY (`SEASON_ID`)
);

CREATE TABLE `teams`(
`TEAM_ID` BIGINT,
`TEAM`VARCHAR(50),
PRIMARY KEY (`TEAM_ID`)
);

CREATE TABLE `stats`(
`ID_STAT_TEAM_SEASON` BIGINT NOT NULL,
`TEAM_ID` BIGINT NOT NULL,
`SEASON_ID` BIGINT NOT NULL,
`GP`INT,
`W`INT,
`L` INT,
`WIN_PERCENT` FLOAT,
`MINUTES` FLOAT,
`PTS` FLOAT,
`FGM` FLOAT,
`FGA` FLOAT,
`FG_PERCENT` FLOAT,
`THREE_PM` FLOAT, 
`THREE_PA` FLOAT,
`THREE_POINT_PERCENT` FLOAT,
`FTM` FLOAT, 
`FTA` FLOAT,
`FT_PERCENT` FLOAT,
`OREB` FLOAT,
`DREB` FLOAT,
`REB` FLOAT, 
`AST` FLOAT,
`TOV` FLOAT, 
`STL` FLOAT,
`BLK` FLOAT, 
`BLKA` FLOAT,
`PF` FLOAT,
`PFD` FLOAT,
`PLUS_MINUS` FLOAT,
PRIMARY KEY (`ID_STAT_TEAM_SEASON`),
CONSTRAINT `fk_stats_teams`
	FOREIGN KEY (`TEAM_ID`)
    REFERENCES `teams`(`TEAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_stats_season`
	FOREIGN KEY (`SEASON_ID`)
    REFERENCES `season`(`SEASON_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);